---
services:
  db:
    image: maheshkanaveni25/flm2025:dbimage
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
    deploy:
      replicas: 1

  auth_service:
    image: maheshkanaveni25/flm2025:authimage
    ports:
      - "5001:5001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: library_db
    depends_on:
      - db

  book_service:
    image: maheshkanaveni25/flm2025:bookimage
    ports:
      - "5002:5002"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: library_db
    depends_on:
      - db

  borrow_service:
    image: maheshkanaveni25/flm2025:borrowimage
    ports:
      - "5003:5003"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: library_db
    depends_on:
      - db

  app_service:
    image: maheshkanaveni25/flm2025:appimage
    ports:
      - "5000:5000"
    depends_on:
      - auth_service
      - book_service
      - borrow_service
